services: 
    web:
      image: jonmazzh/grupo13:1.0.0
      ports:
        - 8443:8443
      environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.110.169:3306/grupo_13
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      depends_on:
        db:
          condition: service_healthy
    db:
      image: jonmazzh/mysql:9.2
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=grupo_13
      volumes:
        - db_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 5s
        timeout: 5s
        start_period: 10s
        retries: 5
volumes:
  db_data: